name: AKS settings Applyment
on:
  workflow_dispatch:
    inputs:
      deployedEnvironment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [uat, test]
        default: uat

permissions:
  security-events: write
  actions: read
  contents: read
  issues: write
  id-token: write

jobs:
  Deployment-pipiline:
    uses: aoda-zhang/shared-devops/.github/workflows/shared_aks_applyment.yaml@master
    with:
      currentEnvironment: ${{inputs.deployedEnvironment}}
      target_config_path: k8sSettings/${{inputs.deployedEnvironment }}
    secrets:
      PAT: ${{ secrets.PAT }}
      AKS_NAMESPACE: ${{ secrets[format('AKS_NAMESPACE_{0}', inputs.deployedEnvironment)] }}
      AZURE_CREDS: ${{ secrets.AZURE_CREDS_DEV }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_DEV }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME_DEV }}
