name: Deployment-pipiline （Non Prod）
on:
  # Only auto deploy when push to develope branch
  # push:
  #   branches: develope
  #   paths-ignore:
  #     - "**/.github/**"
  #     - "**/*.txt"
  #     - "**/*.MD"
  #     - "**/*.md"
  workflow_dispatch:
    inputs:
      deployedEnvironment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [uat, test]
        default: uat
      deployedApp:
        description: "The app name to deploy"
        required: true
        type: choice
        options: [apps/auth, apps/security]

permissions:
  security-events: write
  actions: read
  contents: read
  issues: write

jobs:
  Deployment-pipiline:
    uses: aoda-zhang/shared-devops/.github/workflows/shared_delivery_pipline.yaml@master
    with:
      app_repository: ${{ github.repository }}
      app_branch: ${{ github.ref }}
      deployed_app: ${{ inputs.deployedApp }}
      deploye_type: WEBAPP
      config_path: ${{inputs.deployedApp}}
      currentEnvironment: ${{inputs.deployedEnvironment}}
      dockerfile_path: k8s-base/Dockerfile
    secrets:
      PAT: ${{ secrets.PAT }}
      # Dynamic get secrets by environment example,like DOCKER_SERVER_UAT,DOCKER_SERVER_TEST
      # DOCKER_SERVER: ${{ secrets[format('DOCKER_SERVER_{0}', inputs.deployedEnvironment)] }}
      DOCKER_SERVER: ${{ secrets.DOCKER_SERVER_DEV }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME_DEV }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_DEV }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_DEV }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME_DEV }}
      AKS_NAMESPACE: ${{ secrets.AKS_NAMESPACE_DEV }}
